server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    # 每隔10s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 10000
  client:
    healthcheck:
      enabled: true
    instance:
      hostname: peer1
    service-url:
      defaultZone: http://peer2:8769/eureka/